[package]
name = "node-primitives"
version = "0.18.1"
authors = ["Airalab <research@aira.life>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://robonomics.network"
repository = "https://github.com/airalab/robonomics" 

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { version = "2.0.0-alpha.8", default-features = false }
sp-runtime = { version = "2.0.0-alpha.8", default-features = false }

[dev-dependencies]
sp-serializer = "2.0.0-alpha.8"
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
    "sp-core/std",
    "sp-runtime/std",
]
