[package]
name = "pallet-robonomics-datalog"
description = "Robonomics Network data logging Substrate runtime module"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/akru/substrate", default-features = false }
sp-runtime = { git = "https://github.com/akru/substrate", default-features = false }
frame-system = { git = "https://github.com/akru/substrate", default-features = false }
frame-support = { git = "https://github.com/akru/substrate", default-features = false }
pallet-timestamp = { git = "https://github.com/akru/substrate", default-features = false }

[dev-dependencies]
base58 = "0.1.0"
sp-io = { git = "https://github.com/akru/substrate" }
sp-core = { git = "https://github.com/akru/substrate" }
node-primitives = { git = "https://github.com/akru/substrate" }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-system/std",
    "frame-support/std",
    "pallet-timestamp/std",
]
