[package]
name = "robonomics-ros-api"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
base58 = "0.1"
rosrust = "0.9"
futures = "0.3.1"
futures-util = "0.3.1"
futures-timer = "2"
derive_more = "0.99"
codec = { package = "parity-scale-codec", version = "1.0.0" }
msgs = { package = "robonomics-msgs", path = "../msgs" }
sc-client = { git = "https://github.com/airalab/substrate" }
sc-keystore = { git = "https://github.com/airalab/substrate" }
sp-api = { git = "https://github.com/airalab/substrate" }
sp-core = { git = "https://github.com/airalab/substrate" }
sp-runtime = { git = "https://github.com/airalab/substrate" }
sp-blockchain = { git = "https://github.com/airalab/substrate" }
sp-transaction-pool = { git = "https://github.com/airalab/substrate" }
frame-system = { git = "https://github.com/airalab/substrate" }
pallet-robonomics-storage = { path = "../frame/storage" }
pallet-robonomics-provider = { path = "../frame/provider" }
pallet-robonomics-liability = { path = "../frame/liability" }
pallet-robonomics-agent-runtime-api = { path = "../frame/agent/runtime-api" }

[features]
default = ["agent"]
agent = []
liability = []
blockchain = []
