[package]
name = "robonomics-ros-api"
description = "Robonomics Network ROS API module"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
base58 = "0.1"
rosrust = "0.9"
futures = "0.3.1"
futures-util = "0.3.1"
futures-timer = "2"
derive_more = "0.99"
codec = { package = "parity-scale-codec", version = "1.3" }
msgs = { package = "robonomics-ros-msgs", path = "msgs" }
sc-client = "0.8.0-alpha.6"
sc-keystore = "2.0.0-alpha.6"
sp-api = "2.0.0-alpha.6"
sp-core = "2.0.0-alpha.6"
sp-runtime = "2.0.0-alpha.6"
sp-blockchain = "2.0.0-alpha.6"
sp-transaction-pool = "2.0.0-alpha.6"
frame-system = "2.0.0-alpha.6"
pallet-robonomics-datalog = { path = "../frame/datalog" }
pallet-robonomics-liability = { path = "../frame/liability" }

[features]
default = ["agent"]
agent = []
liability = []
blockchain = []
