[package]
name = "robonomics-ros-api"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
base58 = "0.1"
rosrust = "0.9"
futures = "0.3.1"
futures-util = "0.3.1"
futures-timer = "2"
derive_more = "0.99"
msgs = { package = "robonomics-msgs", path = "../msgs" }
pallet-robonomics-agent-runtime-api = { path = "../frame/agent/runtime-api" }
robonomics-liability = { path = "../liability" }
node-runtime = { path = "../../bin/node/runtime" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
node-primitives = { git = "https://github.com/paritytech/substrate" }
frame-system = { git = "https://github.com/paritytech/substrate" }
pallet-balances = { git = "https://github.com/paritytech/substrate" }
sc-client = { git = "https://github.com/paritytech/substrate" }
sc-keystore = { git = "https://github.com/paritytech/substrate" }
sp-api = { git = "https://github.com/paritytech/substrate" }
sp-core = { git = "https://github.com/paritytech/substrate" }
sp-runtime = { git = "https://github.com/paritytech/substrate" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate" }
