[package]
name = "substrate-ros-player_codegen"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
proc-macro2 = "1.0.0"
syn = "1.0.5"
log = "0.4"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat", "async-await", "nightly"] }
msgs = { package = "substrate-ros-msgs", path = "../msgs" }
