[package]
name = "substrate-ros-api"
version = "0.3.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
hex = "0.4"
rosrust = "0.9.2"
futures = "0.3.1"
futures-timer = "2"
serde_json = "1.0"
codec = { package = "parity-scale-codec", version = "1.0" }

sp-api = { git = "https://github.com/paritytech/substrate" }
sp-core = { git = "https://github.com/paritytech/substrate" }
sp-runtime = { git = "https://github.com/paritytech/substrate" }
sp-session = { git = "https://github.com/paritytech/substrate" }
sp-blockchain = { git = "https://github.com/paritytech/substrate" }
sp-state-machine = { git = "https://github.com/paritytech/substrate" }

sc-rpc = { git = "https://github.com/paritytech/substrate" }
sc-client = { git = "https://github.com/paritytech/substrate" }
sc-client-api = { git = "https://github.com/paritytech/substrate" }
sc-network = { git = "https://github.com/paritytech/substrate" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate" }

msgs = { package = "substrate-ros-msgs", path = "../msgs" }
