[package]
name = "substrate-ros-api"
version = "0.4.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
hex = "0.4"
rosrust = "0.9"
futures = "0.3"
futures-timer = "2"
serde_json = "1.0"
codec = { package = "parity-scale-codec", version = "1.3.0" }

sp-api = "2.0.0-alpha.6"
sp-core = "2.0.0-alpha.6"
sp-runtime = "2.0.0-alpha.6"
sp-session = "2.0.0-alpha.6"
sp-blockchain = "2.0.0-alpha.6"
sp-chain-spec = "2.0.0-alpha.6"
sp-state-machine = "0.8.0-alpha.6"

sc-rpc = "2.0.0-alpha.6"
sc-client = "0.8.0-alpha.6"
sc-client-api = "2.0.0-alpha.6"
sc-network = "0.8.0-alpha.6"
sp-transaction-pool = "2.0.0-alpha.6"

msgs = { package = "substrate-ros-msgs", path = "../msgs" }
