[package]
name = "substrate-ros-api"
version = "0.2.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
rosrust = "0.9"
serde_json = "1.0"
futures = "0.3.1"
futures-timer = "2"
codec = { package = "parity-scale-codec", version = "1.0" }
msgs = { package = "substrate-ros-msgs", path = "../msgs" }
client = { package = "sc-client", git = "https://github.com/paritytech/substrate" }
service = { package = "sc-service", git = "https://github.com/paritytech/substrate" }
network = { package = "sc-network", git = "https://github.com/paritytech/substrate" }
keystore = { package = "sc-keystore", git = "https://github.com/paritytech/substrate" }
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate" }
sc-rpc = { git = "https://github.com/paritytech/substrate" }
sp-runtime = { git = "https://github.com/paritytech/substrate" }
sp-state-machine = { git = "https://github.com/paritytech/substrate" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate" }
