sudo: false
language: rust
cache: cargo
rust:
  - nightly-2019-07-20

matrix:
  include:
  - os: linux 
  - os: osx
  - os: windows

install:
- rustup target add wasm32-unknown-unknown --toolchain nightly-2019-07-20
- cargo install --git https://github.com/alexcrichton/wasm-gc --force

script:
- travis_wait 180 cargo build --release --locked

notifications:
  email:
    on_success: never
