[workspace]
members = [
  "bin/node/cli",
  "bin/node/runtime",
  "substrate-ros/rpc",
  "substrate-ros/msgs",
  "substrate-ros/robonomics",
  "substrate-ros/player_codegen"
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
