[package]
name = "robonomics-node"
version = "0.2.0"
authors = ["Airalab <research@aira.life>"]
build = "build.rs"

[[bin]]
name = "robonomics-node"
path = "src/main.rs"

[dependencies]
error-chain = "0.12"
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1.7"
exit-future = "0.1"
parking_lot = "0.4"
hex-literal = "0.1"
slog = "^2"
parity-codec = { version = "2.1" }
trie-root = { git = "https://github.com/paritytech/trie" }
sr-io = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
sr-primitives = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-cli = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-executor = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-service = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-network = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-consensus-aura = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-client = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa", default-features = false }
substrate-finality-grandpa = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-basic-authorship = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
robonomics-node-runtime = { path = "runtime" }
node-executor = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
structopt = "0.2.13"

[build-dependencies]
vergen = "2"

[workspace]
members = [ "runtime" ]
exclude = [ "runtime/wasm" ]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
