[workspace]
default-members = [ "bin/node/cli" ]
members = [
    "bin/subkey",
    "bin/node/cli",
    "bin/node/executor",
    "bin/node/ipci-runtime",
    "bin/node/robonomics-runtime",
    "robonomics/liability",
    "robonomics/liability/player-codegen",
    "robonomics/frame/agent",
    "robonomics/frame/agent/runtime-api",
    "robonomics/frame/storage",
    "robonomics/frame/provider",
    "robonomics/frame/liability",
    "robonomics/msgs",
    "robonomics/ros-api",
    "substrate-ros/api",
    "substrate-ros/msgs",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
