[workspace]
default-members = [ "bin/node/cli" ]
members = [
    "bin/node/executor",
    "bin/node/runtime",
    "bin/node/cli",
    "robonomics/liability/player-codegen",
    "robonomics/liability",
    "robonomics/frame/liability",
    "robonomics/frame/provider",
    "robonomics/ros-api",
    "robonomics/msgs",
    "substrate-ros/msgs",
    "substrate-ros/api",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
