[package]
name = "liability-player-codegen"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
log = "0.4"
syn = "1.0.5"
quote = "1.0.2"
proc-macro2 = "1.0.0"
futures = { version = "0.3.1", features = ["compat"] }
robonomics-msgs = { path = "../../msgs" }
