[package]
name = "robonomics-node-runtime"
version = "0.2.0"
authors = ["Airalab <research@aira.life>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
parity-codec = "2.0"
parity-codec-derive = "2.0"
sr-std = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
sr-io = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
srml-support = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-keyring = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
srml-balances = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
srml-consensus = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
srml-aura = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
srml-executive = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
sr-primitives = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
srml-system = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
srml-timestamp = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
srml-upgrade-key = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-client = { git = "https://github.com/paritytech/substrate", optional = true, rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
sr-version = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }
substrate-consensus-aura-primitives = { git = "https://github.com/paritytech/substrate", rev = "8b0e5d7ca8b3bf4ae2ad26d773e466d5bc30cbaa" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-executive/std",
	"srml-aura/std",
	"sr-primitives/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-upgrade-key/std",
	"sr-version/std",
	"serde_derive",
	"serde/std",
	"safe-mix/std",
	"substrate-client",
	"substrate-consensus-aura-primitives/std",
]
