[package]
name = "node-cli"
version = "0.14.0"
authors = ["Airalab <research@aira.life>"]
description = "Robonomics node implementation in Rust & Substrate."
build = "build.rs"
edition = "2018"
default-run = "robonomics"

[[bin]]
name = "robonomics"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "airalab/substrate-node-robonomics" }
is-it-maintained-open-issues = { repository = "airalab/substrate-node-robonomics" }

[dependencies]
# third-party dependencies
futures01 = "0.1.29"
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
serde_json = "1.0"
log = "0.4.8"
structopt = "0.3.3"
jsonrpc-core = "13.2.0"

# primitives
node-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate" } 
sp-consensus-babe = { git = "https://github.com/paritytech/substrate" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate" }
sp-core = { git = "https://github.com/paritytech/substrate" }
sp-runtime = { git = "https://github.com/paritytech/substrate" }
sp-consensus = { git = "https://github.com/paritytech/substrate" }
sp-inherents = { git = "https://github.com/paritytech/substrate" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate" }

# client dependencies
sc-client = { git = "https://github.com/paritytech/substrate" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate" }
sc-network = { git = "https://github.com/paritytech/substrate" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate" }
sc-basic-authority = { git = "https://github.com/paritytech/substrate" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate" }
sc-service = { git = "https://github.com/paritytech/substrate", default-features = false }
sc-telemetry = { git = "https://github.com/paritytech/substrate" }
sc-keystore = { git = "https://github.com/paritytech/substrate" }

# frame dependencies
pallet-im-online = { git = "https://github.com/paritytech/substrate" }

# node-specific dependencies
node-runtime = { path = "../runtime" }
node-executor = { path = "../executor" }
sc-executor = { git = "https://github.com/paritytech/substrate" }
sc-rpc = { git = "https://github.com/paritytech/substrate" }

# CLI-specific dependencies
tokio = { version = "0.1.22", optional = true }
exit-future = { version = "0.1.4", optional = true }
ctrlc = { version = "3.0", features = ["termination"], optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", optional = true }

# Browser bundle build support
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { git = "https://github.com/paritytech/substrate", optional = true }

# Robonomics-specific dependencies
rosrust = { version = "0.9.2", optional = true }
substrate-ros-api = { path = "../../../substrate-ros/api", optional = true }
robonomics-ros-api = { path = "../../../robonomics/ros-api", optional = true }

[build-dependencies]
sc-cli = { git = "https://github.com/paritytech/substrate" }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate" }
structopt = "0.3.3"
vergen = "3.0.4"

[features]
default = ["cli","wasmtime"]
rocksdb = ["sc-service/rocksdb"]
wasmtime = [
    "node-executor/wasmtime",
    "sc-service/wasmtime",
    "sc-cli/wasmtime",
]

## Enable Console Line Interface basic features.
cli = [
    "ctrlc",
    "tokio",
    "sc-cli",
    "rocksdb",
    "exit-future",
]

## Enable browser bundle features.
browser = [
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "browser-utils",
]

## Enable ROS integration: exports to ROS topics and services for Robonomics communication.
# To build with it install ROS (http://wiki.ros.org/melodic/Installation) before.
# It also require roscore service to be launched.
ros = [
    "rosrust",
    "substrate-ros-api",
#    "robonomics-ros-api",
]
