[package]
name = "node-cli"
version = "0.17.0"
authors = ["Airalab <research@aira.life>"]
description = "Robonomics node implementation in Rust & Substrate."
build = "build.rs"
edition = "2018"
license = "Apache-2.0"
homepage = "https://robonomics.network"
repository = "https://github.com/airalab/robonomics" 
default-run = "robonomics"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "airalab/robonomics" }
is-it-maintained-open-issues = { repository = "airalab/robonomics" }

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[[bin]]
name = "robonomics"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
futures = { version = "0.3" }
serde = { version = "1.0", features = ["derive"]}
codec = { package = "parity-scale-codec", version = "1.3" }
hex-literal = "0.2"
serde_json = "1.0"
log = "0.4"
structopt = { version = "0.3.8", optional = true }
jsonrpc-core = "13.2.0"

# primitives
node-primitives = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch", default-features = false }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }

# client dependencies
sc-client = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch", default-features = false }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }

# frame dependencies
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch", optional = true }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }

# cumulus dependencies
cumulus-consensus = { git = "https://github.com/paritytech/cumulus" }
cumulus-collator = { git = "https://github.com/paritytech/cumulus" }

# polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot" }
polkadot-collator = { git = "https://github.com/paritytech/polkadot" }
polkadot-service = { git = "https://github.com/paritytech/polkadot" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot" }

# node-specific dependencies
robonomics-runtime = { path = "../robonomics-runtime" }
ipci-runtime = { path = "../ipci-runtime" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch"  }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }

# CLI-specific dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch", optional = true }

# Browser bundle build support
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = "substrate-browser-utils", git = "https://github.com/paritytech/substrate", branch = "cumulus-branch", optional = true }

# Robonomics-specific dependencies
rosrust = { version = "0.9", optional = true }
substrate-ros-api = { path = "../../../substrate-ros/api", optional = true }
robonomics-ros-api = { path = "../../../robonomics/ros-api", optional = true }
robonomics-protocol = { path = "../../../robonomics/protocol", optional = true }

[build-dependencies]
ipci-runtime = { path = "../ipci-runtime" }
robonomics-runtime = { path = "../robonomics-runtime" }
robonomics-protocol = { path = "../../../robonomics/protocol", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch", optional = true }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "cumulus-branch" }
vergen = { version = "3.0.4", optional = true }
structopt = { version = "0.3.8", optional = true }
platforms = { version = "0.2.1", optional = true }

[features]
default = ["wasmtime"]

## Enable Wasmtime virtual machine.
wasmtime = [
    "sc-service/wasmtime",
    "sc-cli/wasmtime",
    "cli",
]

## Enable Console Line Interface basic features.
cli = [
    "sc-cli",
    "vergen",
    "structopt",
    "platforms",
    "sc-service/rocksdb",
    "robonomics-protocol/cli",
]

## Enable browser bundle features.
browser = [
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "browser-utils",
]

## Enable ROS integration: exports to ROS topics and services for Robonomics communication.
# To build with it install ROS (http://wiki.ros.org/melodic/Installation) before.
# It also require roscore service to be launched.
ros = [
    "rosrust",
    "substrate-ros-api",
    "robonomics-ros-api",
]

## Enable runtime benchmarking support.
runtime-benchmarks = [
    "robonomics-runtime/runtime-benchmarks",
    "ipci-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
    "frame-benchmarking",
]
