[package]
name = "node-cli"
version = "0.19.0"
authors = ["Airalab <research@aira.life>"]
description = "Robonomics node implementation in Rust & Substrate."
build = "build.rs"
edition = "2018"
license = "Apache-2.0"
homepage = "https://robonomics.network"
repository = "https://github.com/airalab/robonomics" 
default-run = "robonomics"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "airalab/robonomics" }
is-it-maintained-open-issues = { repository = "airalab/robonomics" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "robonomics"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
futures = { version = "0.3.4" }
serde = { version = "1.0.106", features = ["derive"]}
codec = { package = "parity-scale-codec", version = "1.3.0" }
hex-literal = "0.2"
serde_json = "1.0"
log = "0.4"
structopt = { version = "0.3.8", optional = true }
jsonrpc-core = "13.2.0"

# primitives
node-primitives = { path = "../primitives", default-features = false }
sp-authority-discovery = "2.0.0-rc5"
sp-consensus = "0.8.0-rc5"
sp-consensus-babe = "0.8.0-rc5"
sp-finality-grandpa = "2.0.0-rc5"
sp-api = "2.0.0-rc5"
sp-core = "2.0.0-rc5"
sp-session = "2.0.0-rc5"
sp-runtime = "2.0.0-rc5"
sp-offchain = "2.0.0-rc5"
sp-inherents = "2.0.0-rc5"
sp-timestamp = "2.0.0-rc5"
sp-blockchain = "2.0.0-rc5"
sp-block-builder = "2.0.0-rc5"
sp-transaction-pool = "2.0.0-rc5"

# client dependencies
sc-authority-discovery = "0.8.0-rc5"
sc-basic-authorship = "0.8.0-rc5"
sc-chain-spec = "2.0.0-rc5"
sc-client-db = "0.8.0-rc5"
sc-client-api = "2.0.0-rc5"
sc-consensus = "0.8.0-rc5"
sc-consensus-babe = "0.8.0-rc5"
sc-finality-grandpa = "0.8.0-rc5"
sc-informant = "0.8.0-rc5"
sc-keystore = "2.0.0-rc5"
sc-network = "0.8.0-rc5"
sc-offchain = "2.0.0-rc5"
sc-service = { version = "0.8.0-rc5", default-features = false }
sc-transaction-pool = "2.0.0-rc5"
sc-telemetry = "2.0.0-rc5"

# frame dependencies
pallet-im-online = "2.0.0-rc5"
frame-benchmarking = { version = "2.0.0-rc5", optional = true }
frame-system-rpc-runtime-api = "2.0.0-rc5"
pallet-transaction-payment-rpc-runtime-api = "2.0.0-rc5"

# cumulus dependencies
cumulus-primitives = { git = "https://github.com/akru/cumulus", branch = "crates-io", optional = true }
cumulus-consensus = { git = "https://github.com/akru/cumulus", branch = "crates-io", optional = true }
cumulus-collator = { git = "https://github.com/akru/cumulus", branch = "crates-io", optional = true }
cumulus-network = { git = "https://github.com/akru/cumulus", branch = "crates-io", optional = true }

# polkadot dependencies
polkadot-primitives = { git = "https://github.com/akru/polkadot", branch = "crates-io", optional = true }
polkadot-parachain = { git = "https://github.com/akru/polkadot", branch = "crates-io", optional = true }
polkadot-collator = { git = "https://github.com/akru/polkadot", branch = "crates-io", optional = true }
polkadot-service = { git = "https://github.com/akru/polkadot", branch = "crates-io", optional = true }
polkadot-cli = { git = "https://github.com/akru/polkadot", branch = "crates-io", optional = true }

# node-specific dependencies
node-rpc = { path = "../rpc" }
robonomics-runtime = { path = "../robonomics-runtime" }
ipci-runtime = { path = "../ipci-runtime" }
robonomics-parachain-runtime = { path = "../robonomics-runtime/parachain", optional = true }
sc-executor = "0.8.0-rc5"
sc-rpc = "2.0.0-rc5"

# CLI-specific dependencies
sc-cli = { version = "0.8.0-rc5", optional = true }
frame-benchmarking-cli = { version = "2.0.0-rc5", optional = true }

# Browser bundle build support
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
substrate-browser-utils = { version = "0.8.0-rc5", optional = true }

# Robonomics-specific dependencies
rosrust = { version = "0.9", optional = true }
substrate-ros-api = { path = "../../../substrate-ros/api", optional = true }
robonomics-cli = { path = "../../../robonomics/cli", optional = true }

[build-dependencies]
ipci-runtime = { path = "../ipci-runtime" }
robonomics-runtime = { path = "../robonomics-runtime" }
robonomics-protocol = { path = "../../../robonomics/protocol", optional = true }
sc-cli = { version = "0.8.0-rc5", optional = true }
polkadot-cli = { git = "https://github.com/akru/polkadot", branch = "crates-io", optional = true }
frame-benchmarking-cli = { version = "2.0.0-rc5", optional = true }
substrate-build-script-utils = "2.0.0-rc5"
robonomics-cli = { path = "../../../robonomics/cli", optional = true }
vergen = { version = "3.0.4", optional = true }
structopt = { version = "0.3.8", optional = true }

[features]
default = ["cli","wasmtime","parachain"]

## Enable Wasmtime virtual machine.
wasmtime = [
    "sc-service/wasmtime",
    "sc-cli/wasmtime",
]

## Enable Console Line Interface basic features.
cli = [
    "sc-cli",
    "vergen",
    "structopt",
    "sc-service/db",
    "robonomics-cli",
]

## Enable browser bundle features.
browser = [
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "substrate-browser-utils",
]

## Enable parachain runtime and collator services.
# This feature in additional to Substrate-chain Robonomics runtime
# builds Robonomics as Polkadot parachain.
parachain = [
    "robonomics-parachain-runtime",
    "cumulus-primitives",
    "cumulus-consensus",
    "cumulus-collator",
    "cumulus-network",
    "polkadot-primitives",
    "polkadot-parachain",
    "polkadot-collator",
    "polkadot-service",
    "polkadot-cli",
]

## Enable ROS integration: exports to ROS topics and services for Robonomics communication.
# To build with it install ROS (http://wiki.ros.org/melodic/Installation) before.
# It also require roscore service to be launched.
ros = [
    "rosrust",
    "substrate-ros-api",
]

## Enable runtime benchmarking support.
runtime-benchmarks = [
    "robonomics-runtime/runtime-benchmarks",
    "ipci-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
    "frame-benchmarking",
]
