[package]
name = "robonomics-liability"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
bs58 = "0.2"
rosrust = "0.9"
futures = "0.3.1"
ipfs-api = { git = "https://github.com/akru/rust-ipfs-api" }
robonomics-msgs = { path = "../msgs" }
player-codegen = { package = "liability-player-codegen", path = "./player-codegen" }
