[package]
name = "subkey"
version = "2.0.0-alpha.5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[dependencies]
futures = "0.1.29"
sp-core = "2.0.0-alpha.8"
ipci-runtime = { path = "../node/ipci-runtime" }
node-primitives = { path = "../node/primitives" }
sp-runtime = "2.0.0-alpha.8"
rand = "0.7.2"
clap = "2.33.0"
tiny-bip39 = "0.7"
substrate-bip39 = "0.4.1"
hex = "0.4.0"
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.3.0" }
frame-system = "2.0.0-alpha.8"
pallet-balances = "2.0.0-alpha.8"
pallet-transaction-payment = "2.0.0-alpha.8"
rpassword = "4.0.1"
itertools = "0.8.2"
derive_more = { version = "0.99.2" }
sc-rpc = "2.0.0-alpha.8"
jsonrpc-core-client = { version = "14.0.3", features = ["http"] }
hyper = "0.12.35"
libp2p = "0.16.2"
serde_json = "1.0"

[features]
bench = []

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
