[package]
name = "robonomics-runtime"
version = "0.14.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }

# primitives
node-primitives = { git = "https://github.com/airalab/substrate", default-features = false }
sp-core = { git = "https://github.com/airalab/substrate", default-features = false }
sp-runtime = { git = "https://github.com/airalab/substrate", default-features = false }
sp-staking = { git = "https://github.com/airalab/substrate", default-features = false }
sp-consensus-babe = { git = "https://github.com/airalab/substrate", default-features = false }
sp-offchain = { git = "https://github.com/airalab/substrate", default-features = false }
sp-authority-discovery = { git = "https://github.com/airalab/substrate", default-features = false }
sp-api = { git = "https://github.com/airalab/substrate", default-features = false }
sp-inherents = { git = "https://github.com/airalab/substrate", default-features = false }
sp-block-builder = { git = "https://github.com/airalab/substrate", default-features = false }
sp-transaction-pool = { git = "https://github.com/airalab/substrate", default-features = false }
sp-std = { git = "https://github.com/airalab/substrate", default-features = false }
sp-version = { git = "https://github.com/airalab/substrate", default-features = false }
sp-session = { git = "https://github.com/airalab/substrate", default-features = false }

# frame dependencies
pallet-authorship = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-authority-discovery = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-babe = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-balances = { git = "https://github.com/airalab/substrate", default-features = false }
frame-executive = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-finality-tracker = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-grandpa = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-im-online = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-indices = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-identity = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-society = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-offences = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-session = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-staking = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-staking-reward-curve = { git = "https://github.com/airalab/substrate" }
pallet-sudo = { git = "https://github.com/airalab/substrate", default-features = false }
frame-support = { git = "https://github.com/airalab/substrate", default-features = false }
frame-system = { git = "https://github.com/airalab/substrate", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-utility = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-timestamp = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-transaction-payment = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/airalab/substrate", default-features = false }
pallet-robonomics-agent = { path = "../../../robonomics/frame/agent", default-features = false }
pallet-robonomics-agent-runtime-api = { path = "../../../robonomics/frame/agent/runtime-api", default-features = false }
pallet-robonomics-storage = { path = "../../../robonomics/frame/storage", default-features = false }
pallet-robonomics-provider = { path = "../../../robonomics/frame/provider", default-features = false }
pallet-robonomics-liability = { path = "../../../robonomics/frame/liability", default-features = false }

[build-dependencies]
substrate-wasm-builder-runner = { version = "1.0.4", git = "https://github.com/airalab/substrate" }

[features]
default = ["std"]
ipci = []
parachain = []
std = [
    "codec/std",
    "sp-authority-discovery/std",
    "pallet-authority-discovery/std",
    "pallet-authorship/std",
    "sp-consensus-babe/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "sp-api/std",
    "frame-executive/std",
    "pallet-finality-tracker/std",
    "pallet-grandpa/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "pallet-identity/std",
    "pallet-society/std",
    "node-primitives/std",
    "sp-offchain/std",
    "pallet-offences/std",
    "sp-core/std",
    "pallet-randomness-collective-flip/std",
    "sp-std/std",
    "serde",
    "serde_derive",
    "pallet-session/std",
    "sp-runtime/std",
    "sp-staking/std",
    "pallet-staking/std",
    "sp-session/std",
    "pallet-sudo/std",
    "frame-support/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "pallet-utility/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "sp-version/std",
    "sp-block-builder/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
    "pallet-robonomics-agent/std",
    "pallet-robonomics-agent-runtime-api/std",
    "pallet-robonomics-storage/std",
    "pallet-robonomics-provider/std",
    "pallet-robonomics-liability/std",
]
