[package]
name = "substrate-ros-robonomics"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
bs58 = "0.2"
rosrust = "0.8"
futures = { version = "0.3.1" }
ipfsapi = "0.3.0"
futures-timer = "0.2"
futures01 = { package = "futures", version = "0.1" }
msgs = { package = "substrate-ros-msgs", path = "../msgs" }
node-runtime = { path = "../../bin/node/runtime" }
robonomics-liability = { path = "./liability" }
player_codegen = { package = "substrate-ros-player_codegen", path = "../player_codegen" }
system = { package = "paint-system", git = "https://github.com/paritytech/substrate" }
balances = { package = "paint-balances", git = "https://github.com/paritytech/substrate" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate" }
sr-primitives = { git = "https://github.com/paritytech/substrate" }
transaction-pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate" }
