[package]
name = "robonomics-protocol"
description = "Robonomics Network protocol on libp2p."
version = "0.3.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3", features = ["derive"] }
substrate-subxt = "0.5.0"
sp-core = "2.0.0-alpha.5"
sp-runtime = "2.0.0-alpha.5"
pallet-indices = "2.0.0-alpha.5"
derive_more = "0.99"
bincode = "1.2"
libp2p = "0.18"
log = "0.4"
hex = "0.4"

# cli specified
sc-cli = { git = "https://github.com/paritytech/substrate", optional = true }
structopt = { version = "0.3.8", optional = true }
async-std = { version = "1.5", optional = true }

[features]
default = []

## Enables console interface components.
cli = [
    "structopt",
    "async-std",
    "sc-cli",
]
