[package]
name = "robonomics-protocol"
description = "Robonomics Network protocol library."
version = "0.5.3"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
derive_more = "0.99"
futures-timer = "3.0"
substrate-subxt = "0.8"
substrate-subxt-proc-macro = "0.8"
pallet-indices = "2.0.0-rc2"
sp-runtime = "2.0.0-rc2"
sp-core = "2.0.0-rc2"
libp2p = "0.19"
futures = "0.3.5"
bincode = "1.2"
log = "0.4"
