[package]
name = "robonomics-protocol"
description = "Robonomics Network protocol on libp2p"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
libp2p = { version = "0.16.2" }

[dev-dependencies]
async-std = "1.5"
futures = "0.3"
