[package]
name = "robonomics-protocol"
description = "Robonomics Network protocol on libp2p"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
derive_more = "0.99"
structopt = "0.3.8"
async-std = "1.5"
futures = "0.3"
libp2p = "0.16"
log = "0.4"
