[package]
name = "robonomics-sensors"
description = "Robonomics Network supported sensors."
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
robonomics-protocol = { path = "../protocol" }

# cli specified
sc-cli = { git = "https://github.com/paritytech/substrate", optional = true }
structopt = { version = "0.3.8", optional = true }
async-std = { version = "1.5", optional = true }

[features]
default = []

## Enables console interface components.
cli = [
    "structopt",
    "async-std",
    "sc-cli",
]
