[package]
name = "node-executor"
version = "0.14.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
sc-executor = { git = "https://github.com/paritytech/substrate" }
node-runtime = { path = "../runtime" }

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
