[package]
name = "node-executor"
version = "0.13.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
substrate-executor = { git = "https://github.com/paritytech/substrate" }
node-runtime = { path = "../runtime" }
