[package]
name = "pallet-robonomics-agent-runtime-api"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false }
pallet-robonomics-provider = { path = "../../provider", default-features = false }
pallet-robonomics-liability = { path = "../../liability", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "sp-api/std",
    "sp-runtime/std",
    "frame-system/std",
    "frame-support/std",
    "pallet-robonomics-provider/std",
    "pallet-robonomics-liability/std",
]
