on: [push]

name: Integration

jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Install LLVM (windows only)
      if: runner.os == 'Windows'
      run: choco install llvm
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly-2020-02-02'
        targets: 'wasm32-unknown-unknown'
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Check targets are installed correctly
      run: rustup target list --installed
    - name: Install build tools
      run: cargo install --git https://github.com/alexcrichton/wasm-gc --force
    - name: Build optimized binary
      run: cargo build --release --verbose
    - name: Upload binary into IPFS
      run: |
        tar cfJ robonomics-${{ matrix.os }}-x86_64.tar.xz target/release/robonomics
        curl -F file=@robonomics-#{{ matrix.os }}-x86_64.tar.xz https://ipfs.infura.io:5001/api/v0/add

  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly-2020-02-02'
        targets: 'wasm32-unknown-unknown'
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Check targets are installed correctly
      run: rustup target list --installed
    - name: Install build tools
      run: |
        cargo install --git https://github.com/alexcrichton/wasm-gc --force
        cargo install --git https://github.com/rustwasm/wasm-pack --force
    - name: Build Web Node
      run: make pkg --directory bin/node/browser
    - name: Upload Web Node into IPFS
      run: |
        cd bin/node/browser
        FILES=$(find * -type f | grep -v ' ' | awk -v q="'" '{print " -F " q "file=@\"" $0 "\";filename=\"" $0 "\"" q}')
        curl "https://ipfs.infura.io:5001/api/v0/add?pin=true&recursive=true&wrap-with-directory=true" -X POST -H "Content-Type: multipart/form-data" $FILES
