name: Integration
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly' 
        targets: 'wasm32-unknown-unknown'
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Check targets are installed correctly
      run: rustup target list --installed
    - name: Install wasm-gc tool
      run: cargo install --git https://github.com/alexcrichton/wasm-gc --force
    - name: Build Robonomics on Substrate
      run: cargo build --verbose --bin robonomics
