name: Integration
on: [push]
jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly-2020-02-02'
        targets: 'wasm32-unknown-unknown'
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Check targets are installed correctly
      run: rustup target list --installed
    - name: Install wasm-gc tool
      run: cargo install --git https://github.com/alexcrichton/wasm-gc --force
    - name: Install LLVM (windows only)
      if: runner.os == 'Windows'
      run: choco install llvm 
    - name: Build Robonomics binary
      run: cargo build --verbose

  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly-2020-02-02'
        targets: 'wasm32-unknown-unknown'
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Check targets are installed correctly
      run: rustup target list --installed
    - name: Install wasm-gc tool
      run: cargo install --git https://github.com/alexcrichton/wasm-gc --force
    - name: Install wasm-pack tool
      run: cargo install --git https://github.com/rustwasm/wasm-pack --force
    - name: Build Robonomics Web Node
      run: make pkg --directory bin/node/browser
