name: Testing 
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - name: Run all tests
      run: nix-shell --run "cargo test --all"
