name: Testing 
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly-2020-05-15'
        targets: 'wasm32-unknown-unknown'
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Install build tools
      run: cargo install --git https://github.com/alexcrichton/wasm-gc --force
    - name: Install libudev dependecy
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install libudev-dev
    - name: Install ROS Melodic
      run: ./scripts/ros-install.sh
    - name: Run all tests
      run: cargo test --all
