[package]
name = "pallet-robonomics-liability"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false }
system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false }
support = { package = "frame-support", git = "https://github.com/paritytech/substrate", default-features = false }
indices = { package = "pallet-indices", git = "https://github.com/paritytech/substrate", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate" }
sp-core = { git = "https://github.com/paritytech/substrate" }
node-primitives = { git = "https://github.com/paritytech/substrate" }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "sp-runtime/std",
    "system/std",
    "support/std",
]
