[package]
name = "pallet-robonomics-liability"
description = "Robonomics Network Robot Liability Substrate runtime module"
version = "0.4.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
sp-std = "2.0.0-alpha.8"
sp-core = "2.0.0-alpha.8"
sp-runtime = "2.0.0-alpha.8"
sp-arithmetic = "2.0.0-alpha.8"
frame-system = "2.0.0-alpha.8"
frame-support = "2.0.0-alpha.8"

[dev-dependencies]
base58 = "0.1.0"
sp-io = "2.0.0-alpha.8"
node-primitives = { path = "../../../bin/node/primitives" } 

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-arithmetic/std",
    "frame-system/std",
    "frame-support/std",
]
